version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
            name: Restaurando pacotes
            command: dotnet restore
      - run:
            name: Compilando aplicação
            command: dotnet build
      - run: 
            name: Executando testes
            command: dotnet test --no-build